/**
 * Populates a database with plausible review history so the dashboard can be
 * explored - and screenshotted - without connecting a real repository.
 *
 *   npx tsx scripts/seed-demo.ts [--database data/demo.sqlite] [--days 90]
 *
 * The generator is seeded from a fixed constant, so the same command always
 * produces the same history. That matters for the screenshots in `docs/`: they
 * can be regenerated byte-for-byte rather than being a one-off artefact nobody
 * can reproduce.
 *
 * The shape it models is a team that inherits some debt, ships steadily, has a
 * couple of bad weeks, then starts paying findings down - which is what makes
 * the trend charts worth looking at. Nothing here is real data.
 */

import { createHash } from 'node:crypto';
import { rmSync } from 'node:fs';
import { ReviewStore, type RecordableFinding } from '../src/storage/database';
import type { Category, Severity } from '../src/analysis/types';

interface RuleTemplate {
  ruleId: string;
  category: Category;
  severity: Severity;
  title: string;
  /** Relative likelihood of this rule firing. Common mistakes are common. */
  weight: number;
}

const RULES: RuleTemplate[] = [
  { ruleId: 'sql-injection/interpolated-query', category: 'sql-injection', severity: 'critical', title: 'SQL query built by string interpolation', weight: 5 },
  { ruleId: 'sql-injection/string-concatenation', category: 'sql-injection', severity: 'critical', title: 'SQL query built by string concatenation', weight: 4 },
  { ruleId: 'secrets/aws-access-key-id', category: 'secrets', severity: 'critical', title: 'AWS access key committed to the repository', weight: 2 },
  { ruleId: 'secrets/hardcoded-credential', category: 'secrets', severity: 'high', title: 'Hardcoded credential', weight: 6 },
  { ruleId: 'authentication/jwt-decode-without-verify', category: 'authentication', severity: 'critical', title: 'JWT decoded without verifying its signature', weight: 3 },
  { ruleId: 'authentication/weak-password-hash', category: 'authentication', severity: 'high', title: 'Fast general-purpose hash used on a credential', weight: 4 },
  { ruleId: 'authentication/insecure-cookie-flags', category: 'authentication', severity: 'medium', title: 'Session cookie missing its protective flags', weight: 7 },
  { ruleId: 'authentication/tls-verification-disabled', category: 'authentication', severity: 'high', title: 'TLS certificate verification disabled', weight: 3 },
  { ruleId: 'authorization/missing-ownership-check', category: 'authorization', severity: 'high', title: 'Record fetched by client-supplied ID with no ownership check', weight: 8 },
  { ruleId: 'authorization/mass-assignment', category: 'authorization', severity: 'high', title: 'Request body written onto a model wholesale', weight: 5 },
  { ruleId: 'authorization/unprotected-state-changing-route', category: 'authorization', severity: 'high', title: 'State-changing route registered without an auth check', weight: 6 },
  { ruleId: 'dependencies/known-vulnerable-version', category: 'dependencies', severity: 'high', title: 'Dependency affected by a published advisory', weight: 9 },
  { ruleId: 'dependencies/unbounded-version-range', category: 'dependencies', severity: 'medium', title: 'Dependency has no upper version bound', weight: 5 },
  { ruleId: 'dangerous-api/shell-exec', category: 'dangerous-api', severity: 'critical', title: 'Shell command built from untrusted input', weight: 3 },
  { ruleId: 'dangerous-api/eval', category: 'dangerous-api', severity: 'high', title: 'Dynamic code evaluation', weight: 4 },
  { ruleId: 'dangerous-api/ssrf', category: 'dangerous-api', severity: 'high', title: 'Outbound request to a user-supplied URL', weight: 5 },
  { ruleId: 'dangerous-api/weak-cipher', category: 'dangerous-api', severity: 'medium', title: 'Weak or misused cipher', weight: 6 },
  { ruleId: 'dangerous-api/insecure-temp-file', category: 'dangerous-api', severity: 'low', title: 'Predictable temporary file path', weight: 4 },
];

const REPOSITORIES = [
  { fullName: 'acme/payments-api', activity: 1.0, files: ['src/billing/invoices.ts', 'src/billing/charges.ts', 'src/auth/session.ts', 'src/db/queries.ts', 'package.json'] },
  { fullName: 'acme/web-app', activity: 0.8, files: ['app/routes/profile.tsx', 'app/routes/admin.tsx', 'app/lib/api.ts', 'app/lib/render.ts', 'package.json'] },
  { fullName: 'acme/platform-infra', activity: 0.45, files: ['terraform/network.tf', 'terraform/iam.tf', 'scripts/deploy.sh', 'requirements.txt'] },
];

const AUTHORS = ['ansh', 'priya', 'marcus', 'lena', 'devon'];

/**
 * Demo findings are content-addressed the same way real ones are: identity comes
 * from where and what, not from which scan happened to see it. Without this, the
 * same vulnerable line produces a brand-new fingerprint on every sighting, dozens
 * of distinct findings pile up on one line, and a single later review that
 * examines that line closes all of them at once - a spike that exists only in
 * the generator.
 */
function demoFingerprint(repository: string, path: string, line: number, ruleId: string): string {
  // security-review-ignore-next-line authentication/weak-password-hash
  // A content address for deduplication, mirroring the real fingerprint - not a
  // credential hash, so a fast digest is the right choice.
  return createHash('sha256')
    .update(`${repository} ${path} ${line} ${ruleId}`)
    .digest('hex')
    .slice(0, 20);
}

/**
 * Verdicts for the demo data. Two rules are deliberately noisy - a predictable
 * temp file and a weak cipher are the classic findings that are usually fine in
 * context - so the accuracy panel has a real pattern to point at rather than
 * uniform noise.
 */
const NOISY_RULES = new Set([
  'dangerous-api/insecure-temp-file',
  'dangerous-api/weak-cipher',
  'dependencies/unbounded-version-range',
]);

function pickVerdict(ruleId: string, random: () => number): string {
  const roll = random();
  if (NOISY_RULES.has(ruleId)) {
    if (roll < 0.6) return 'refuted';
    if (roll < 0.8) return 'unclear';
    return 'likely';
  }
  if (roll < 0.08) return 'refuted';
  if (roll < 0.2) return 'unclear';
  if (roll < 0.55) return 'likely';
  return 'confirmed';
}

/** Deterministic LCG, so a given seed always yields the same history. */
function makeRandom(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
    return state / 0x100000000;
  };
}

function parseArgs(argv: string[]): { databasePath: string; days: number; seed: number } {
  const get = (flag: string): string | undefined => {
    const index = argv.indexOf(flag);
    return index >= 0 ? argv[index + 1] : undefined;
  };
  return {
    databasePath: get('--database') ?? 'data/demo.sqlite',
    days: Number.parseInt(get('--days') ?? '90', 10),
    seed: Number.parseInt(get('--seed') ?? '20260827', 10),
  };
}

function main(): void {
  const { databasePath, days, seed } = parseArgs(process.argv.slice(2));
  const random = makeRandom(seed);

  // Start from scratch so re-running is idempotent rather than cumulative.
  if (databasePath !== ':memory:') {
    for (const suffix of ['', '-journal', '-wal', '-shm']) {
      try {
        rmSync(`${databasePath}${suffix}`);
      } catch {
        // Nothing to remove on a first run.
      }
    }
  }

  const store = new ReviewStore(databasePath);
  const db = store.connection;
  const totalWeight = RULES.reduce((sum, rule) => sum + rule.weight, 0);

  const pickRule = (): RuleTemplate => {
    let roll = random() * totalWeight;
    for (const rule of RULES) {
      roll -= rule.weight;
      if (roll <= 0) return rule;
    }
    return RULES[0]!;
  };

  const backdate = db.prepare(
    "UPDATE scans SET created_at = datetime('now', ?) WHERE id = ?",
  );
  const backdateFindings = db.prepare(
    "UPDATE findings SET created_at = datetime('now', ?) WHERE scan_id = ?",
  );
  /**
   * `recordScan` stamps `resolved_at` with the current time, which is right in
   * production and wrong here: without backdating it too, every resolution the
   * reviewer inferred across the whole simulated history lands on today and the
   * flow chart shows one implausible spike at the right-hand edge.
   */
  const backdateResolution = db.prepare(
    `UPDATE finding_state
        SET resolved_at = datetime('now', ?)
      WHERE repository_id = ? AND fingerprint = ?`,
  );
  const backdateState = db.prepare(
    `UPDATE finding_state
        SET first_seen_at = datetime('now', ?), last_seen_at = datetime('now', ?)
      WHERE repository_id = ? AND fingerprint = ? AND first_seen_at > datetime('now', ?)`,
  );
  /**
   * Resolves a bounded number of the oldest open findings. Expressed as a
   * subquery because `UPDATE ... LIMIT` is not available in every SQLite build,
   * and an unbounded UPDATE here is what produces a single implausible spike
   * that flattens the whole chart.
   */
  const resolveOldest = db.prepare(
    `UPDATE finding_state
        SET status = 'resolved', resolved_at = datetime('now', ?)
      WHERE rowid IN (
        SELECT rowid FROM finding_state
         WHERE repository_id = ?
           AND status = 'open'
           AND first_seen_at <= datetime('now', ?)
         ORDER BY first_seen_at
         LIMIT ?
      )`,
  );

  let sequence = 0;
  let scans = 0;

  for (const repository of REPOSITORIES) {
    const repositoryId = store.repositoryId(repository.fullName);

    for (let day = days - 1; day >= 0; day -= 1) {
      const offset = `-${day} days`;
      const progress = 1 - day / days;
      const weekday = (day % 7) < 5;

      // Two rough phases: things get worse while the team ships fast, then
      // better once the reviewer is taken seriously. Weekends are quiet.
      const pressure = progress < 0.55 ? 1.25 : 0.55;
      const reviewsToday = weekday
        ? Math.floor(random() * 4 * repository.activity) + (random() < 0.5 ? 1 : 0)
        : Math.floor(random() * 1.4 * repository.activity);

      for (let review = 0; review < reviewsToday; review += 1) {
        sequence += 1;

        /**
         * A real pull request edits a handful of contiguous hunks, and the
         * reviewer only examines those lines. Modelling that faithfully matters
         * here: if the demo data claimed every review examined scattered lines
         * across the whole file, later reviews would keep colliding with old
         * findings and resolve them wholesale, and the trend would collapse to
         * zero instead of showing a backlog being worked down.
         */
        const touched = 1 + Math.floor(random() * 2.5 * repository.activity);
        const hunks: { path: string; start: number; span: number }[] = [];
        for (let index = 0; index < touched; index += 1) {
          hunks.push({
            path: repository.files[Math.floor(random() * repository.files.length)]!,
            start: 10 + Math.floor(random() * 900),
            span: 4 + Math.floor(random() * 14),
          });
        }

        const findings: RecordableFinding[] = [];
        const findingCount = Math.floor(random() * 2.6 * pressure);
        const seenThisScan = new Set<string>();
        for (let index = 0; index < findingCount; index += 1) {
          const rule = pickRule();
          const hunk = hunks[Math.floor(random() * hunks.length)]!;
          const line = hunk.start + Math.floor(random() * hunk.span);
          // One scan never reports the same issue at the same place twice.
          const key = `${hunk.path}:${line}:${rule.ruleId}`;
          if (seenThisScan.has(key)) continue;
          seenThisScan.add(key);
          findings.push({
            ruleId: rule.ruleId,
            category: rule.category,
            severity: rule.severity,
            confidence: random() < 0.65 ? 'high' : random() < 0.7 ? 'medium' : 'low',
            title: rule.title,
            description: 'Generated by scripts/seed-demo.ts for demonstration purposes.',
            remediation: 'Generated by scripts/seed-demo.ts for demonstration purposes.',
            filePath: hunk.path,
            line,
            snippet: '(demonstration data - no real source code)',
            fingerprint: demoFingerprint(repository.fullName, hunk.path, line, rule.ruleId),
            // Some findings carry a triage verdict, so the accuracy panel has
            // something to show. Noisier rules get refuted more often, which is
            // the pattern that panel exists to surface.
            ...(random() < 0.55
              ? {
                  triage: {
                    verdict: pickVerdict(rule.ruleId, random),
                    confidence: random() < 0.7 ? 'high' : 'medium',
                    model: 'demonstration-model',
                  },
                }
              : {}),
          });
        }

        const examinedByPath = new Map<string, Set<number>>();
        for (const hunk of hunks) {
          const lines = examinedByPath.get(hunk.path) ?? new Set<number>();
          for (let line = hunk.start; line < hunk.start + hunk.span; line += 1) lines.add(line);
          examinedByPath.set(hunk.path, lines);
        }

        const result = store.recordScan({
          repositoryFullName: repository.fullName,
          pullRequestNumber: 100 + sequence,
          headSha: `${sequence.toString(16).padStart(8, '0')}${'0'.repeat(32)}`,
          baseSha: 'a'.repeat(40),
          title: PR_TITLES[sequence % PR_TITLES.length]!,
          author: AUTHORS[Math.floor(random() * AUTHORS.length)]!,
          filesScanned: examinedByPath.size,
          durationMs: 200 + Math.floor(random() * 1400),
          findings,
          examined: [...examinedByPath].map(([path, lines]) => ({ path, lines: [...lines] })),
        });
        scans += 1;

        backdate.run(offset, result.scanId);
        backdateFindings.run(offset, result.scanId);
        for (const fingerprint of result.resolvedFingerprints) {
          backdateResolution.run(offset, repositoryId, fingerprint);
        }
        for (const finding of findings) {
          // Only move a finding's first-seen date back if this scan introduced
          // it; a repeat sighting must not rewrite the original date.
          backdateState.run(offset, offset, repositoryId, finding.fingerprint, offset);
        }
      }

      // Remediation: more of it later in the window, and never a mass sweep.
      const appetite = progress < 0.5 ? 0.2 : 0.6;
      if (weekday && random() < appetite) {
        const cleared = 1 + Math.floor(random() * 3);
        resolveOldest.run(offset, repositoryId, offset, cleared);
      }
    }
  }

  const open = db
    .prepare<[], { count: number }>("SELECT COUNT(*) AS count FROM finding_state WHERE status = 'open'")
    .get()!.count;
  const resolved = db
    .prepare<[], { count: number }>("SELECT COUNT(*) AS count FROM finding_state WHERE status = 'resolved'")
    .get()!.count;

  store.close();

  process.stdout.write(
    `Seeded ${databasePath} with ${scans} reviews across ${REPOSITORIES.length} repositories ` +
      `over ${days} days: ${open} open findings, ${resolved} resolved.\n` +
      `Run it with:  DATABASE_PATH=${databasePath} ALLOW_INSECURE_WEBHOOK=true npm start\n`,
  );
}

const PR_TITLES = [
  'Add invoice export endpoint',
  'Fix pagination on the charges list',
  'Bump dependencies',
  'Support partial refunds',
  'Add admin impersonation',
  'Cache customer lookups',
  'Move session store to Redis',
  'Add webhook retry queue',
  'Tighten the IAM policy',
  'Rework the profile page',
  'Add CSV import',
  'Split the deploy script',
  'Add rate limiting',
  'Migrate to the new auth provider',
  'Add audit logging',
];

main();
